### ISSUE TITLE
mopp_rl crashes

### ISSUE THREAD

**Issue by Romern** [Ormin/skyblivion-NIFConverter#1]
Python 3.3.0
PyFFI 2.2.0
PHP 5.6.24
Windows 10 64bit

I can run it with "-c none" just fine, but with "mopp", "mopp_new" or "convex" mopp_rl.exe  crashes with exit code 3. Other people seem to have similar issues, even with Windows XP SP3: https://tesrenewal.com/forums/skyblivion-problems/any-tutorial-on-how-to-use-the-nif-converter
Is mopp_rl.exe broken? It also crashes with no parameters given.

**Comment by Ormin** [comment]
Hey there - I never really intended to release it so it might be that it's crashing in many stupid situations. Sorry for that!

One thing I remember that MIGHT affect things is that I recall that I had a NIF template file in a fixed location, maybe thats why? I'll take a closer look, maybe I'll find something.

**Comment by Ormin** [comment]
Btw do you have any kind of dump from the crash?

**Comment by Romern** [comment]
Thank you for the quick reply, here is the output:

```
C:\Users\RK\Downloads\skyblivion-NIFConverter>python convert_folder.py C:\Users\RK\Downloads\skyblivion-NIFConverter\testfolder C:\Users\RK\Downloads\skyblivion-NIFConverter\testfolder_out -s default -c mopp
MOPP_RL.exe uses havok. Copyright 1999-2013 Havok.com Inc. (and its Licensors).
All Rights Reserved. See www.havok.com for details.
Converting C:\Users\RK\Downloads\skyblivion-NIFConverter\testfolder\anvilaltar01.nif
Traceback (most recent call last):
  File "copyover_legacy_nif_animations.py", line 1362, in <module>
    parser.parse()
  File "copyover_legacy_nif_animations.py", line 361, in parse
    parser.parse_node(root, root)
  File "copyover_legacy_nif_animations.py", line 893, in parse_node
    self.parse_collision(node)
  File "copyover_legacy_nif_animations.py", line 225, in parse_collision
    self.parse_shape(rigidbody.shape, None)
  File "copyover_legacy_nif_animations.py", line 1351, in parse_shape
    self.arbitrary_moppgen(shape))
  File "copyover_legacy_nif_animations.py", line 82, in arbitrary_moppgen
    check_output(['mopp_rl', temppath, temppathoutput])
  File "C:\Python33\lib\subprocess.py", line 584, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['mopp_rl', 'C:\\Users\\RK\\Downloads\\skyblivion-NIFConverter\\testfolder_out\\anvilaltar01.nif_temp_mopptemp', 'C:\\Users\\RK\\Downloads\\skyblivion-NIFConverter\\testfolder_out\\anvilaltar01.nif_temp_mopptempoutput']' returned non-zero exit status 3
C:\Users\RK\Downloads\skyblivion-NIFConverter\testfolder\anvilaltar01.nif conversion failed!
```

I will try to create a crashdump.

**Comment by Ormin** [comment]
K, I found it I think, I forgot to attach the template.nif to the project, so sorry about that!

Pull the latest master and read the readme ( you have to copy the new template.nif file to C:\template.nif ). Sorry about inconvenience!

**Comment by Romern** [comment]
Thank you, now it's working perfectly!

**Comment by Ormin** [comment]
Wonderful, glad to hear that! Sorry that it took so long :P
